### PR TITLE
Add ability to traverse through Shadow DOM

### PR DESCRIPTION
**Pull request by arminbashizade**
- add ally.js to observe mutation from shadow DOMs ([docs](https://allyjs.io/api/observe/shadow-mutations.html))
- add recursive method to get active element
- update `traverse` to dive into children or `shadowRoot`'s children
- recreate AOM tree when observed mutation includes addition/deletion of shadow roots

test on this page: https://js-odeam3.stackblitz.io ([source code](https://stackblitz.com/edit/js-odeam3?file=index.js))

### CODE REVIEW

**Comment by ziolko** [comment]
@arminbashizade This is great stuff. I am shocked that so little code was required to support shadow DOM. Thanks for this contribution and sorry for the late reply.

Unfortunately, the test page you've provided doesn't seem to contain any content. I will test it on https://www.webcomponents.org/ and if everything is good I will merge and release it either today or tomorrow.

**Comment by arminbashizade** [comment]
@ziolko my bad I'd forgot to save the files in Stackblitz 😅 you can try again now

**Comment by ziolko** [comment]
This is obviously a great improvement. Unfortunately, due to https://github.com/WICG/webcomponents/issues/204 it fails to observe shadow DOM roots created after ARIA DevTools was enabled on the page (you can see an example at https://stackblitz.com/edit/js-ukrqkc?file=index.js). Do you have an idea how this could be improved?

Anyway, I'd like to merge and release this change. I keep list of contributors at https://github.com/ziolko/aria-devtools#contributors- . Are you OK with adding you there?

**Comment by arminbashizade** [comment]
> This is obviously a great improvement. Unfortunately, due to [WICG/webcomponents#204](https://github.com/WICG/webcomponents/issues/204) it fails to observe shadow DOM roots created after ARIA DevTools was enabled on the page (you can see an example at https://stackblitz.com/edit/js-ukrqkc?file=index.js). Do you have an idea how this could be improved?

@ziolko I pushed some changes that would recreate the AOM tree when observed mutation includes addition/deletion of shadow roots, not sure if that's the most efficient way or if I can update just part of the tree, though.

> Anyway, I'd like to merge and release this change. I keep list of contributors at https://github.com/ziolko/aria-devtools#contributors- . Are you OK with adding you there?

of course, I'd be happy to be included.

**Comment by ziolko** [comment]
Looks great! I will release it tomorrow and should appear on Chrome store in the next few days.

**Comment by ziolko** [comment]
@arminbashizade I have released a new version and added you to the list of contributors. Thanks you for this PR and for your help!

**Pull request merged**
