### PR TITLE
Add support for <details> and <summary> tag

### PR DESCRIPTION
**Pull request by mass8326**
Closes: https://github.com/ziolko/aria-devtools/issues/36

Before:
image

After:
image

### CODE REVIEW

**Comment by ziolko** [comment]
Hi @mass8326 thank you for this great contribution! I will test it briefly in the next two or three days and then release :)

**Comment by mass8326** [comment]
I'm very happy to help out! This tool has given me the ability to really improve our website's accessibility and has inspired me to pay much more attention to semantic html elements.

If this saves you any time, here's the two pages I used for reference: [Astro's homepage](https://astro.build/#:~:text=Build%20personal%20and%20professional%20blogs) and [11ty's homepage](https://www.11ty.dev/#:~:text=Eleventy%20requires%20Node.js%2014)

Let me know if you run into any cases or have any suggestions where I can improve the renderer!

**Comment by ziolko** [comment]
@mass8326 sorry that it took longer than expected. I've merged your changes and released a new version to Chrome web store. It should be available in one or two days.

Thank you for help!

**Comment by ziolko** [comment]
@mass8326 I forgot to ask - do you want to be added to the list of contributors in README?

**Comment by mass8326** [comment]
Awesome, thanks for merging it in! I'm excited to be able to better see `<details>` in aria-devtools from now on.

If you added me to the list of contributors, that'd be pretty neat and appreciated!

**Comment by ziolko** [comment]
Perfect, I've updated the project README file to add you to the list of contributors.

Cheers,
Mateusz

**Pull request merged**
