### PR TITLE
Count listitems found in list or child groups.

### PR DESCRIPTION
**Pull request by ctemplin**

### CODE REVIEW

**Comment by ziolko** [comment]
Hi @ctemplin,

Thanks for this great contribution! Let me review it and I will reach you back later today.

Mateusz

**Comment by ctemplin** [comment]
Thank you for such a useful extension!
BTW, I tried to write a test for my change but didn't get far. It seems none of the renderers are being tested, true? Perhaps adding a simple example test would help contributors to get testing.
-Chris

**Comment by ziolko** [comment]
Works great. WRT tests it's true that renderers are not being tested now. As the project grows now I think that's something that will change in the next few months.

I plan to release a new version during the weekend so you can expect this fix to be available next week.

**Comment by ziolko** [comment]
Hi @ctemplin,

I've just released a new version with your fix. It should be publicly available tomorrow or on Tuesday.

Do you want to be added to the list of contributors at https://github.com/ziolko/aria-devtools?

Also, it would be nice if you could star this repository and leave a positive review on the extension page. As this is something I develop in my free time small things like this keep me motivated 😉

Regards,
Mateusz

**Comment by ctemplin** [comment]
Hi @ziolko,
Yes, please do add me to the list. Thanks for the reminder to star and review. Both done now.

**Comment by ziolko** [comment]
Thanks! I've just added you as a contributor to the project readme file.

**Pull request merged**
